Iter13
NikolosHGW/metric pull request #13
Opened 2024-03-15 04:08 UTC by NikolosHGW

2024-03-16 15:23 UTC, Bazys requested changes
перепиши сигнатуру функций, работающих с контекстом.

2024-03-16 15:23 UTC, Bazys commented on internal/server/storage/db.go
> +func (ds DBStorage) SetMetric(m models.Metrics, ctx context.Context) error {
в го принято ВСЕГДА ctx context.Context первым аргументом функции

2024-03-16 15:23 UTC, Bazys commented on internal/server/services/metric.go
>  type repository interface {
с приватным интерфейсом будут проблемы - ты не сможешь его замокать для юнит тестов

2024-03-20 03:57 UTC, NikolosHGW commented on internal/server/storage/db.go
> +func (ds DBStorage) SetMetric(m models.Metrics, ctx context.Context) error {
+

2024-03-20 03:57 UTC, NikolosHGW commented on internal/server/services/metric.go
>  type repository interface {
+

2024-03-20 18:21 UTC, Bazys approved these changes
Вот так выглядит намного красивее.
По самому коду сразу вопросов  не было, только по стилистике

2024-03-21 03:42 UTC, merged