iter14
NikolosHGW/metric pull request #14
Opened 2024-03-27 05:32 UTC by NikolosHGW

2024-04-25 20:15 UTC, Bazys requested changes
1. time.Sleep как-то не по гошному.
2. слишком долги локи мьютексом. ты теряешь все преимущества конкурентности

2024-04-25 20:15 UTC, Bazys commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(config.GetPollInterval()) * time.Second)
ты на такое длинное время блокируешь работу с данными мьютексом!
вот не уверен что именно это ты задумывал.

2024-04-25 20:15 UTC, Bazys commented on cmd/agent/main.go
> +				time.Sleep(time.Duration(reportInterval) * time.Second)
Предпочтение, отдаваемое Go в определенных сценариях `time.NewTicker`, а не `time.Sleep`, обусловлено различиями в их использовании и природой параллельного программирования в Go. Обе функции являются частью пакета `time` и предоставляют механизмы для работы со временем, но они служат разным целям.

### `time.Sleep`

- **Назначение**: `time.Sleep` приостанавливает выполнение текущей goroutine по крайней мере на указанное время. Это простой способ задержать выполнение в одном месте вашего кода.
- **Польза**: Лучше всего использовать, когда вам нужна простая, одноразовая задержка, не требующая повторных действий или точного контроля времени после окончания задержки.
- **Поведение**: Блокирует работу goroutine, делая ее неактивной на время сна, без каких-либо дополнительных накладных расходов или механизма управления.

### `time.NewTicker`

- **Назначение**: `time.NewTicker` создает новый тикер, который будет отправлять время в свой канал через определенные промежутки времени. Он предназначен для тех случаев, когда вам нужно делать что-то многократно через регулярные промежутки времени.
- **Польза**: Это идеальный вариант для повторяющихся действий, когда вам нужно поддерживать постоянную скорость работы, например, для опроса или многократной проверки обновлений. Тикер предоставляет канал, по которому вы можете делать выборку, легко взаимодействуя с моделью параллелизма Go.
- **Поведение**: Позволяет более гибко управлять механизмом синхронизации. Вы можете остановить тикер, по сути, освободив его ресурсы и остановив интервальные операции. Этого нельзя добиться с помощью `time.Sleep`, поскольку sleep не предлагает механизма остановки.

### Сравнение и предпочтения

- **Конкурентность и контроль**: `time.NewTicker` лучше вписывается в модель параллелизма Go, предоставляя канал для диапазона или выбора. Это более идиоматично в Go при работе с повторяющимися действиями с таймером. Он предлагает больше контроля, позволяя вам остановить тикер и предотвратить дальнейшие тики, что невозможно с `time.Sleep`.
- **Управление ресурсами**: Тикеры можно останавливать и очищать, что особенно важно для долго работающих приложений, чтобы предотвратить утечку ресурсов. `time.Sleep` не потребляет дополнительных ресурсов во время сна, но он не предлагает такого контроля и гибкости, как тикеры.
- **Использование в циклах**: Для операций, которые должны выполняться через регулярные промежутки времени, предпочтительнее использовать `time.NewTicker`, поскольку он обеспечивает постоянный интервал между тиками, в то время как использование `time.Sleep` в цикле может привести к смещению во времени из-за времени выполнения основного блока цикла.

В итоге, если `time.Sleep` подходит для простых, разовых задержек, не требующих дополнительного контроля времени, то `time.NewTicker` предпочтительнее для задач, требующих повторного выполнения через фиксированные промежутки времени, предлагая больший контроль и интеграцию с парадигмами параллельного программирования Go. Выбор между `time.Sleep` и `time.NewTicker` зависит от конкретных потребностей вашего приложения в синхронизации и параллельности.

2024-04-26 04:29 UTC, NikolosHGW commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(config.GetPollInterval()) * time.Second)
заменил на ticker

2024-04-26 04:29 UTC, NikolosHGW commented on cmd/agent/main.go
> +				time.Sleep(time.Duration(reportInterval) * time.Second)
заменил на ticker

2024-04-27 15:28 UTC, Bazys approved these changes

2024-04-27 16:11 UTC, merged