Iter18
NikolosHGW/metric pull request #20
Opened 2024-06-11 05:59 UTC by NikolosHGW

2024-06-18 19:49 UTC, Bazys requested changes
1. Покрытие тестами всего 33.5% а должно быть на этом этапе 40
2. преаллоцируй слайсы

2024-06-18 19:49 UTC, Bazys commented on internal/client/request/request.go
>  	var metricsBatch []models.Metrics
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
metricsBatch := make([]Type, 0, len(m.GetMetrics()))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-06-19 06:01 UTC, NikolosHGW commented on internal/client/request/request.go
>  	var metricsBatch []models.Metrics
+

2024-06-25 20:20 UTC, Bazys approved these changes
1. Не обрабатываешь ошибки очень часто
2. Не все слайсы преалоцировал.

Щас не заворачиваю, но к следующему разу поправь.

2024-06-25 20:20 UTC, Bazys commented on cmd/server/config.go
>  func NewConfig() *config {
а почему бы и конфиги в internal не положить?

2024-07-05 06:33 UTC, merged