Iter20
NikolosHGW/metric pull request #22
Opened 2024-07-08 14:46 UTC by NikolosHGW

2024-07-11 19:09 UTC, Bazys requested changes
1. покрытие тестами должно быть 55%, у тебя сейчас 44.3%
2. очень часто не проверяешь ошибки. подключи линтер errcheck

2024-07-12 04:25 UTC, NikolosHGW commented
![image](https://github.com/user-attachments/assets/06af96be-6ad1-490b-a0b1-aeb5fe143a3c)
У меня же покрытие 58.9%

2024-07-12 05:57 UTC, NikolosHGW commented
Использую команды go test -coverprofile=coverage.out ./... и go tool cover -func=coverage.out. Сейчас показывается результат покрытия 56.3%
![image](https://github.com/user-attachments/assets/7af41873-f055-4b2d-9d0d-6d50cb39cd29)

2024-07-14 11:23 UTC, Bazys commented on internal/static/config.go
> +type StaticConfig struct {
снаружи это выглядит как `static.StaticConfig` - масло масленое.
подумай над неймингом

1. https://go.dev/blog/package-names
2. https://go.dev/doc/effective_go#names
3. https://google.github.io/styleguide/go/decisions.html

2024-07-14 11:26 UTC, Bazys commented on internal/server/storage/disk.go
>  		if err := Producer.WriteMetric(&metric); err != nil {
у тебя 1.21 версися гошечки - по ссылке лучше не обращаться.
либо перейди на 1.22, либо используй замыкание.

2024-07-14 11:29 UTC, Bazys requested changes
1. есть пара вопросов.
2. я првереяю покрытие следующей командой:
```sh
#!/bin/bash
go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=count ./...
go tool cover -func coverage.out

```

2024-07-15 04:12 UTC, merged