Iter25
NikolosHGW/metric pull request #27
Opened 2024-08-16 04:27 UTC by NikolosHGW

2024-08-18 22:10 UTC, Bazys requested changes
пара вопросов.По самому  заданию нет особвх вопросов

2024-08-18 22:10 UTC, Bazys commented on internal/server/interceptor/decrypt.go
> +	info *grpc.UnaryServerInfo,
Параметр функции, названный `info`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `info` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-08-18 22:10 UTC, Bazys commented on internal/client/request/request.go
> +	localAddr := conn.LocalAddr().(*net.UDPAddr)
а вдруг там не то что ожидаешь? проаерить через ок?

2024-08-18 22:10 UTC, Bazys commented on cmd/server/main.go
> +	"github.com/NikolosHGW/metric/internal/proto"
импорты не отсортированы, сначала stdlib, затем внешние пакеты, а уж затем твои.

2024-08-19 04:39 UTC, NikolosHGW commented on internal/server/interceptor/decrypt.go
> +	info *grpc.UnaryServerInfo,
+

2024-08-19 04:39 UTC, NikolosHGW commented on internal/client/request/request.go
> +	localAddr := conn.LocalAddr().(*net.UDPAddr)
+

2024-08-19 04:39 UTC, NikolosHGW commented on cmd/server/main.go
> +	"github.com/NikolosHGW/metric/internal/proto"
+

2024-08-19 09:02 UTC, Bazys approved these changes
настройки гоимпортс еще подкрути, надо указать какие пакеты твои

2024-08-19 09:02 UTC, Bazys commented on cmd/agent/main.go
> +	"google.golang.org/grpc"
более тонкая настройка нужна

2024-08-22 03:17 UTC, merged