Iter5
NikolosHGW/metric pull request #5
Opened 2023-11-23 04:59 UTC by NikolosHGW

2023-11-26 15:17 UTC, Bazys requested changes
Почитай и примени Dependency Injection. 
У тебя хорошее начало положено с интеhфейсом `Storage`, вот только не надо каждый раз его передавать в качестве параметра.
Сделай хендлер структурой и инжектируй в него интерфейс хранилища, а далее реализацию можно будет подменять.
Почитай вот здесь для начала (это не обязательное руководство к действию, это только для старта): [раз](https://github.com/evrone/go-clean-template#dependency-injection), [два](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/dependency-injection), [три](https://dev.to/dryrainbow/dependency-injection-in-golang-35oa)

2023-11-26 15:17 UTC, Bazys commented on internal/server/handlers/handlers.go
> +		rootDir, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}").Output()
а если запускать на той машине где не установлен golang?
Зачем все это? зачем шаблоны хранить в `internal`

2023-11-30 04:55 UTC, NikolosHGW commented on internal/server/handlers/handlers.go
> +		rootDir, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}").Output()
+

2023-11-30 15:34 UTC, Bazys approved these changes
Начало положено, давай продвигаться по пути DI дальше.
Сейчас принимаю, к следующему разу продолжай дорабатывать.

2023-11-30 15:34 UTC, Bazys commented on internal/client/config/config.go
> +type netAddress struct {
тут ты пишешь свой велосипед https://pkg.go.dev/net/url#URL

2023-11-30 15:34 UTC, Bazys commented on internal/server/services/metric/metric.go
> +func SetMetric(strg storage.Storage, metricType, metricName, metricValue string) {
а вот тут тоже просится на переделку в методы структуры, в которую инжектируется интерфейс `Storage`

2023-12-01 05:22 UTC, NikolosHGW commented on internal/client/config/config.go
> +type netAddress struct {
+

2023-12-02 05:20 UTC, NikolosHGW commented on internal/client/config/config.go
> +type netAddress struct {
+

2023-12-04 05:30 UTC, NikolosHGW commented on internal/server/services/metric/metric.go
> +func SetMetric(strg storage.Storage, metricType, metricName, metricValue string) {
+

2023-12-04 05:33 UTC, merged